export enum Group {
  Assets = "assets",
  Flows = "flows",
  Values = "values",
}

export interface Node {
  id: number;
  name: string;
  group: Group;
}

// The order of the items in the array determine their placement on the chart. The id is irrelevant.
export const nodes: Node[] = [
  { id: 0, name: "Native vegetation", group: Group.Assets },
  { id: 1, name: "Rivers", group: Group.Assets },
  { id: 21, name: "Shelterbelts / windbreaks", group: Group.Assets },
  { id: 22, name: "Croplands", group: Group.Assets },
  { id: 23, name: "Pastures", group: Group.Assets },
  { id: 24, name: "Dam and wetlands", group: Group.Assets },
  { id: 2, name: "Soils", group: Group.Assets },
  { id: 3, name: "Mineral ore", group: Group.Assets },
  { id: 4, name: "Atmospheric gases", group: Group.Assets },
  { id: 5, name: "Timber products", group: Group.Flows },
  { id: 6, name: "Food products", group: Group.Flows },
  { id: 25, name: "Livestock production", group: Group.Flows },
  { id: 19, name: "Beneficial insects", group: Group.Flows },
  { id: 20, name: "Nutrient cycling", group: Group.Flows },
  { id: 7, name: "Biodiversity", group: Group.Flows },
  { id: 8, name: "Visual amenity", group: Group.Flows },
  { id: 9, name: "Metals", group: Group.Flows },
  { id: 10, name: "Water and air filtration", group: Group.Flows },
  { id: 26, name: "Harvestable crops", group: Group.Flows },
  { id: 11, name: "Carbon sequestration", group: Group.Flows },
  { id: 12, name: "Building materials", group: Group.Values },
  { id: 13, name: "Manufacturing", group: Group.Values },
  { id: 14, name: "Climate regulation", group: Group.Values },
  { id: 15, name: "Food security", group: Group.Values },
  { id: 16, name: "Tourism and recreation", group: Group.Values },
  { id: 17, name: "Clean water and air", group: Group.Values },
  { id: 27, name: "Fibre and other materials", group: Group.Values },
  { id: 28, name: "Reduced soil loss", group: Group.Values },
  { id: 29, name: "Pollination and pest control", group: Group.Values },
  { id: 18, name: "Nature conservation", group: Group.Values },
];

export const manufacturingLinks = [
  [0, 5],
  [0, 6],
  [0, 7],
  [0, 11],
  [0, 8],
  [0, 10],
  [1, 7],
  [1, 8],
  [1, 6],
  [2, 6],
  [2, 11],
  [2, 10],
  [2, 7],
  [3, 9],
  [4, 7],
  [4, 6],
  [5, 12],
  [5, 13],
  [6, 15],
  [6, 16],
  [7, 18],
  [7, 17],
  [7, 16],
  [7, 14],
  [8, 16],
  [8, 18],
  [9, 12],
  [9, 13],
  [10, 14],
  [10, 17],
  [11, 14],
] as [number, number][];

export const foodLinks = [
  [0, 19],
  [0, 20],
  [0, 11],
  [0, 7],
  [21, 25],
  [21, 19],
  [21, 11],
  [21, 7],
  [22, 26],
  [22, 20],
  [22, 7],
  [23, 25],
  [23, 20],
  [23, 19],
  [23, 7],
  [24, 25],
  [24, 20],
  [24, 26],
  [24, 7],
  [2, 20],
  [2, 19],
  [2, 11],
  [25, 15],
  [25, 27],
  [19, 15],
  [19, 29],
  [19, 18],
  [20, 15],
  [20, 28],
  [20, 14],
  [7, 18],
  [7, 28],
  [26, 15],
  [26, 27],
  [11, 14],
] as [number, number][];
